## â–‘â–ˆâ–€â–€â–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–ˆâ–€â–€â–‘â–ˆâ–‘â–ˆâ–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆ
## â–‘â–€â–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–€â–€â–ˆâ–‘â–ˆâ–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–€
## â–‘â–€â–€â–€â–‘â–‘â–€â–‘â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–‘

# Sets user-defined palette
palette = "catppuccin_mocha"

# Setups
# format="$directory$git_branch$character$line_break"
# right_format = """$git_status$cmd_duration$line_break"""
# format="$directory$git_branch$fill$ocaml$golang$nodejs$line_break$character"
format="$directory$git_branch$all$line_break$character"
# right_format = "$all"
add_newline = true

# [line_break]
# disabled = true 
[fill]
symbol = ' '
style = 'bold green'

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = " [î©±](green bold)"
error_symbol = "[îª¼](pink)"
vicmd_symbol = "[îŸ…](peach)"

[directory]
# format = "[î‚¶]($style)[î—¿ ](bg:base fg:pink)[$path](bg:base fg:lavender bold)[î‚´ ]($style)"
format = "($style)(bg:base fg:pink)[$path](bg:base fg:lavender bold)($style)"
style = "bg:none fg:base"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[î‚¶]($style)[[î¬§ ](bg:base fg:green bold)$branch](bg:base fg:lavender)[î‚´ ]($style)"
style = "bg:none fg:base"

# [git_status]
# conflicted = 'ğŸ³'
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ˜°'
# diverged = 'ğŸ˜µ'
# up_to_date = 'âœ“'
# untracked = 'ğŸ¤·'
# stashed = 'ğŸ“¦'
# modified = 'ğŸ“'
# staged = '[++\($count\)](green)'
# renamed = 'ğŸ‘…'
# deleted = 'ğŸ—‘'

# [git_status]
# # $all status$ahead_behind
# format = "[î‚¶]($style)[$all_status$ahead_behind](bg:base fg:yellow)[î‚´ ]($style)"
# style = "bg:none fg:base"
# conflicted = "="
# ahead =	"â‡¡${count}"
# behind = "â‡£${count}"
# diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
# up_to_date = 'âœ“'
# untracked = "?${count}"
# stashed = 'ğŸ“¦'
# modified = "!${count}"
# staged = "+${count}"
# renamed = "Â»${count}"
# deleted = "ï™•${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[î‚¶]($style)[(bg:base fg:flamingo bold)$duration](bg:base fg:text)[î‚´ ]($style)"
disabled = false
style = "bg:none fg:base"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[golang]
format = 'via [$symbol$version](bold cyan) '

[nodejs]
format = 'via [ğŸ¤– $version](bold green) '

[ocaml]
format = 'via [$symbol$version]($style) '
